/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Task
    /// </summary>
    [DataContract]
    public partial class Task :  IEquatable<Task>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Task" /> class.
        /// </summary>
        /// <param name="TaskId">TaskId.</param>
        /// <param name="TaskName">TaskName.</param>
        /// <param name="TaskSubject">TaskSubject.</param>
        /// <param name="TaskDescription">TaskDescription.</param>
        /// <param name="TaskStatus">TaskStatus.</param>
        /// <param name="TaskPriority">TaskPriority.</param>
        /// <param name="TaskIsSkipable">TaskIsSkipable.</param>
        /// <param name="TaskCreatedOn">TaskCreatedOn.</param>
        /// <param name="TaskActivationTime">TaskActivationTime.</param>
        /// <param name="TaskProcInstId">TaskProcInstId.</param>
        /// <param name="TaskProcDefId">TaskProcDefId.</param>
        /// <param name="TaskContainerId">TaskContainerId.</param>
        /// <param name="TaskParentId">TaskParentId.</param>
        public Task(int TaskId = default(int), string TaskName = default(string), string TaskSubject = default(string), string TaskDescription = default(string), string TaskStatus = default(string), int? TaskPriority = default(int?), bool? TaskIsSkipable = default(bool?), long? TaskCreatedOn = default(long?), long? TaskActivationTime = default(long?), int? TaskProcInstId = default(int?), string TaskProcDefId = default(string), string TaskContainerId = default(string), int? TaskParentId = default(int?))
        {
            this.TaskId = TaskId;
            this.TaskName = TaskName;
            this.TaskSubject = TaskSubject;
            this.TaskDescription = TaskDescription;
            this.TaskStatus = TaskStatus;
            this.TaskPriority = TaskPriority;
            this.TaskIsSkipable = TaskIsSkipable;
            this.TaskCreatedOn = TaskCreatedOn;
            this.TaskActivationTime = TaskActivationTime;
            this.TaskProcInstId = TaskProcInstId;
            this.TaskProcDefId = TaskProcDefId;
            this.TaskContainerId = TaskContainerId;
            this.TaskParentId = TaskParentId;
        }
        
        /// <summary>
        /// Gets or Sets TaskId
        /// </summary>
        [DataMember(Name="task-id", EmitDefaultValue=false)]
        public int TaskId { get; set; }
        /// <summary>
        /// Gets or Sets TaskName
        /// </summary>
        [DataMember(Name="task-name", EmitDefaultValue=false)]
        public string TaskName { get; set; }
        /// <summary>
        /// Gets or Sets TaskSubject
        /// </summary>
        [DataMember(Name="task-subject", EmitDefaultValue=false)]
        public string TaskSubject { get; set; }
        /// <summary>
        /// Gets or Sets TaskDescription
        /// </summary>
        [DataMember(Name="task-description", EmitDefaultValue=false)]
        public string TaskDescription { get; set; }
        /// <summary>
        /// Gets or Sets TaskStatus
        /// </summary>
        [DataMember(Name="task-status", EmitDefaultValue=false)]
        public string TaskStatus { get; set; }
        /// <summary>
        /// Gets or Sets TaskPriority
        /// </summary>
        [DataMember(Name="task-priority", EmitDefaultValue=false)]
        public int? TaskPriority { get; set; }
        /// <summary>
        /// Gets or Sets TaskIsSkipable
        /// </summary>
        [DataMember(Name="task-is-skipable", EmitDefaultValue=false)]
        public bool? TaskIsSkipable { get; set; }
        /// <summary>
        /// Gets or Sets TaskCreatedOn
        /// </summary>
        [DataMember(Name="task-created-on", EmitDefaultValue=false)]
        public long? TaskCreatedOn { get; set; }
        /// <summary>
        /// Gets or Sets TaskActivationTime
        /// </summary>
        [DataMember(Name="task-activation-time", EmitDefaultValue=false)]
        public long? TaskActivationTime { get; set; }
        /// <summary>
        /// Gets or Sets TaskProcInstId
        /// </summary>
        [DataMember(Name="task-proc-inst-id", EmitDefaultValue=false)]
        public int? TaskProcInstId { get; set; }
        /// <summary>
        /// Gets or Sets TaskProcDefId
        /// </summary>
        [DataMember(Name="task-proc-def-id", EmitDefaultValue=false)]
        public string TaskProcDefId { get; set; }
        /// <summary>
        /// Gets or Sets TaskContainerId
        /// </summary>
        [DataMember(Name="task-container-id", EmitDefaultValue=false)]
        public string TaskContainerId { get; set; }
        /// <summary>
        /// Gets or Sets TaskParentId
        /// </summary>
        [DataMember(Name="task-parent-id", EmitDefaultValue=false)]
        public int? TaskParentId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Task {\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  TaskName: ").Append(TaskName).Append("\n");
            sb.Append("  TaskSubject: ").Append(TaskSubject).Append("\n");
            sb.Append("  TaskDescription: ").Append(TaskDescription).Append("\n");
            sb.Append("  TaskStatus: ").Append(TaskStatus).Append("\n");
            sb.Append("  TaskPriority: ").Append(TaskPriority).Append("\n");
            sb.Append("  TaskIsSkipable: ").Append(TaskIsSkipable).Append("\n");
            sb.Append("  TaskCreatedOn: ").Append(TaskCreatedOn).Append("\n");
            sb.Append("  TaskActivationTime: ").Append(TaskActivationTime).Append("\n");
            sb.Append("  TaskProcInstId: ").Append(TaskProcInstId).Append("\n");
            sb.Append("  TaskProcDefId: ").Append(TaskProcDefId).Append("\n");
            sb.Append("  TaskContainerId: ").Append(TaskContainerId).Append("\n");
            sb.Append("  TaskParentId: ").Append(TaskParentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Task);
        }

        /// <summary>
        /// Returns true if Task instances are equal
        /// </summary>
        /// <param name="other">Instance of Task to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Task other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TaskId == other.TaskId ||
                    this.TaskId != null &&
                    this.TaskId.Equals(other.TaskId)
                ) && 
                (
                    this.TaskName == other.TaskName ||
                    this.TaskName != null &&
                    this.TaskName.Equals(other.TaskName)
                ) && 
                (
                    this.TaskSubject == other.TaskSubject ||
                    this.TaskSubject != null &&
                    this.TaskSubject.Equals(other.TaskSubject)
                ) && 
                (
                    this.TaskDescription == other.TaskDescription ||
                    this.TaskDescription != null &&
                    this.TaskDescription.Equals(other.TaskDescription)
                ) && 
                (
                    this.TaskStatus == other.TaskStatus ||
                    this.TaskStatus != null &&
                    this.TaskStatus.Equals(other.TaskStatus)
                ) && 
                (
                    this.TaskPriority == other.TaskPriority ||
                    this.TaskPriority != null &&
                    this.TaskPriority.Equals(other.TaskPriority)
                ) && 
                (
                    this.TaskIsSkipable == other.TaskIsSkipable ||
                    this.TaskIsSkipable != null &&
                    this.TaskIsSkipable.Equals(other.TaskIsSkipable)
                ) && 
                (
                    this.TaskCreatedOn == other.TaskCreatedOn ||
                    this.TaskCreatedOn != null &&
                    this.TaskCreatedOn.Equals(other.TaskCreatedOn)
                ) && 
                (
                    this.TaskActivationTime == other.TaskActivationTime ||
                    this.TaskActivationTime != null &&
                    this.TaskActivationTime.Equals(other.TaskActivationTime)
                ) && 
                (
                    this.TaskProcInstId == other.TaskProcInstId ||
                    this.TaskProcInstId != null &&
                    this.TaskProcInstId.Equals(other.TaskProcInstId)
                ) && 
                (
                    this.TaskProcDefId == other.TaskProcDefId ||
                    this.TaskProcDefId != null &&
                    this.TaskProcDefId.Equals(other.TaskProcDefId)
                ) && 
                (
                    this.TaskContainerId == other.TaskContainerId ||
                    this.TaskContainerId != null &&
                    this.TaskContainerId.Equals(other.TaskContainerId)
                ) && 
                (
                    this.TaskParentId == other.TaskParentId ||
                    this.TaskParentId != null &&
                    this.TaskParentId.Equals(other.TaskParentId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TaskId != null)
                    hash = hash * 59 + this.TaskId.GetHashCode();
                if (this.TaskName != null)
                    hash = hash * 59 + this.TaskName.GetHashCode();
                if (this.TaskSubject != null)
                    hash = hash * 59 + this.TaskSubject.GetHashCode();
                if (this.TaskDescription != null)
                    hash = hash * 59 + this.TaskDescription.GetHashCode();
                if (this.TaskStatus != null)
                    hash = hash * 59 + this.TaskStatus.GetHashCode();
                if (this.TaskPriority != null)
                    hash = hash * 59 + this.TaskPriority.GetHashCode();
                if (this.TaskIsSkipable != null)
                    hash = hash * 59 + this.TaskIsSkipable.GetHashCode();
                if (this.TaskCreatedOn != null)
                    hash = hash * 59 + this.TaskCreatedOn.GetHashCode();
                if (this.TaskActivationTime != null)
                    hash = hash * 59 + this.TaskActivationTime.GetHashCode();
                if (this.TaskProcInstId != null)
                    hash = hash * 59 + this.TaskProcInstId.GetHashCode();
                if (this.TaskProcDefId != null)
                    hash = hash * 59 + this.TaskProcDefId.GetHashCode();
                if (this.TaskContainerId != null)
                    hash = hash * 59 + this.TaskContainerId.GetHashCode();
                if (this.TaskParentId != null)
                    hash = hash * 59 + this.TaskParentId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
