/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TaskSummary
    /// </summary>
    [DataContract]
    public partial class TaskSummary :  IEquatable<TaskSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskSummary" /> class.
        /// </summary>
        /// <param name="_TaskSummary">_TaskSummary.</param>
        public TaskSummary(List<Task> _TaskSummary = default(List<Task>))
        {
            this._TaskSummary = _TaskSummary;
        }
        
        /// <summary>
        /// Gets or Sets _TaskSummary
        /// </summary>
        [DataMember(Name="task-summary", EmitDefaultValue=false)]
        public List<Task> _TaskSummary { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaskSummary {\n");
            sb.Append("  _TaskSummary: ").Append(_TaskSummary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TaskSummary);
        }

        /// <summary>
        /// Returns true if TaskSummary instances are equal
        /// </summary>
        /// <param name="other">Instance of TaskSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskSummary other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._TaskSummary == other._TaskSummary ||
                    this._TaskSummary != null &&
                    this._TaskSummary.SequenceEqual(other._TaskSummary)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._TaskSummary != null)
                    hash = hash * 59 + this._TaskSummary.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
