swagger: '2.0'
info:
  version: 1.0-SNAPSHOT
  title: KieServerTaskManager
host: 10.52.36.21:8080
basePath: /kie-server/services/rest
schemes:
  - http
securityDefinitions:
  tokenAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /server/containers/{containerId}/tasks/{tInstanceId}/states/claimed:
    put:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{containerId}/tasks/{tInstanceId}/states/started:
    put:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{containerId}/tasks/{tInstanceId}/states/completed:
    put:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            type: object
            additionalProperties:
                type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
            
  /server/containers/{containerId}/tasks/{tInstanceId}/states/failed:
    put:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{containerId}/tasks/{tInstanceId}:
    get:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
        - type: boolean
          name: withInputData
          in: query
          required: false
        - type: boolean
          name: withOutputData
          in: query
          required: false
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/TaskInstance"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/queries/tasks/instances/process/{pInstanceId}:
    get:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: integer
          name: pInstanceId
          in: path
          required: true
        - type: integer
          name: page
          in: query
          required: false
        - type: integer
          name: pageSize
          in: query
          required: false
        - type: string
          name: status
          in: query
          required: false
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/TaskSummaries"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
            
  /server/queries/tasks/instances/pot-owners:
    get:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: array
          items:
            type: string
          name: groups
          in: query
          required: false
        - type: integer
          name: page
          in: query
          required: false
        - type: integer
          name: pageSize
          in: query
          required: false
        - type: string
          name: sort
          in: query
          required: false
        - type: boolean
          name: sortOrder
          in: query
          required: false
        - type: array
          items:
            type: string
          name: status
          in: query
          required: false
        - type: string
          name: user
          in: query
          required: false
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/TaskSummaries"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/queries/definitions/{queryName}:
    post:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            $ref: "#/definitions/Query"
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
    delete:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/queries/definitions/{queryName}/filtered-data:
    post:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
        - type: string
          name: mapper
          in: query
          required: true
          enum: 
            - UserTasksWithCustomVariables
            - UserTasksWithVariables
            - UserTasks
            - ProcessInstancesWithCustomVariables
            - ProcessInstancesWithVariables
            - ProcessInstances
            - TaskSummaries
            - RawList
        - type: integer
          name: pageSize
          in: query
          required: false
        - type: integer
          name: page
          in: query
          required: false
        - name: filter
          in: body
          required: false
          schema:
            $ref: '#/definitions/Filter'
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: object
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

definitions:
  TaskStatus:
    type: string
    enum:
      - Created
      - Ready
      - Reserved
      - InProgress
      - Completed
      - Failed
      - Error
      - Exited
      - Obsolete
      
  Mapper:
    type: string
    enum: 
      - UserTasksWithCustomVariables
      - UserTasksWithVariables
      - UserTasks
      - ProcessInstancesWithCustomVariables
      - ProcessInstancesWithVariables
      - ProcessInstances
      - TaskSummaries
      - RawList

  Query:
    type: object
    properties:
      query-name:
        type: string
      query-source:
        type: string
      query-expression:
        type: string
      query-target:
        type: string
        
  Filter:
    type: object
    properties:
      order-by:
        type: string
      order-asc:
        type: boolean
      query-params:
        type: array
        items:
          type: object
          properties:
            cond-column:
              type: string
            cond-operator:
              type: string
              enum: 
                - IS_NULL
                - NOT_NULL
                - EQUALS_TO
                - NOT_EQUALS_TO
                - LIKE_TO
                - GREATER_THAN
                - GREATER_OR_EQUALS_TO
                - LOWER_THAN
                - LOWER_OR_EQUALS_TO
                - BETWEEN
                - IN
                - NOT_IN
            cond-values:
              type: array
              items:
                type: string
              
  TaskSummaries:
    type: object
    properties: 
      task-summary: 
        type: array
        items:
          $ref: "#/definitions/TaskSummary"
          
  TaskSummary:
    type: object
    properties:
      task-id:
        type: integer
      task-name:
        type: string
      task-subject:
        type: string
      task-description:
        type: string
      task-status:
        type: string
      task-priority:
        type: integer
      task-is-skipable:
        type: boolean
      task-created-on:
        type: string
        format: date-time
      task-activation-time:
        type: string
        format: date-time
      task-proc-inst-id:
        type: integer
      task-proc-def-id:
        type: string
      task-container-id:
        type: string
      task-parent-id:
        type: integer
  
  TaskInstances:
    type: object
    properties: 
      task-instance: 
        type: array
        items:
          $ref: "#/definitions/TaskInstance"
        
  TaskInstance:
    type: object
    properties:
      task-id:
        type: integer
      task-priority:
        type: integer
      task-name:
        type: string
      task-subject:
        type: string
      task-description:
        type: string
      task-form:
        type: string
      task-status:
        type: string
      task-actual-owner:
        type: string
      task-created-by:
        type: string
      task-created-on:
        type: string
        format: date-time
      task-activation-time:
        type: string
        format: date-time
      task-skippable:
        type: boolean
      task-workitem-id:
        type: integer
      task-process-instance-id:
        type: integer
      task-parent-id:
        type: integer
      task-process-id:
        type: string
      task-container-id:
        type: string
      task-input-data:      
        type: object
        additionalProperties:
          type: string