swagger: '2.0'
info:
  version: 0.1-SNAPSHOT
  title: project
host: 10.52.36.21:8080
basePath: /kie-server/services/rest
schemes:
  - http
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /server/containers/{containerId}/tasks/{tInstanceId}/states/claimed:
    put:
      security:
        - basicAuth : []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{containerId}/tasks/{tInstanceId}/states/started:
    put:
      security:
        - basicAuth : []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{containerId}/tasks/{tInstanceId}/states/completed:
    put:
      security:
        - basicAuth : []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: tInstanceId
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            type: object
            additionalProperties:
                type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/queries/tasks/instances/pot-owners:
    get:
      security:
        - basicAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: array
          items:
            type: string
          name: groups
          in: query
          required: false
        - type: integer
          name: page
          in: query
          required: false
        - type: integer
          name: pageSize
          in: query
          required: false
        - type: string
          name: sort
          in: query
          required: false
        - type: boolean
          name: sortOrder
          in: query
          required: false
        - type: array
          items:
            type: string
          name: status
          in: query
          required: false
        - type: string
          name: user
          in: query
          required: false
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/TaskSummary"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  '/server/queries/definitions/{queryName}':
    post:
      security:
       - basicAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            $ref: "#/definitions/Query"
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
    delete:
      security:
       - basicAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  '/server/queries/definitions/{queryName}/filtered-data':
    post:
      security:
       - basicAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: queryName
          in: path
          required: true
        - type: string
          name: mapper
          in: query
          required: true
          enum: 
            - UserTasksWithCustomVariables
            - UserTasksWithVariables
            - UserTasks
            - ProcessInstancesWithCustomVariables
            - ProcessInstancesWithVariables
            - ProcessInstances
            - TaskSummaries
            - RawList
        - type: integer
          name: pageSize
          in: query
          required: false
        - name: body
          in: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: object
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
definitions:
  Query:
    type: object
    properties:
      query-name:
        type: string
      query-source:
        type: string
      query-expression:
        type: string
      query-target:
        type: string
  TaskSummary:
    type: object
    properties: 
      task-summary: 
        type: array
        items:
          $ref: "#/definitions/Task"
          
          
  Task:
    type: object
    properties:
      task-id:
        type: integer
      task-name:
        type: string
      task-subject:
        type: string
      task-description:
        type: string
      task-status:
        type: string
      task-priority:
        type: integer
      task-is-skipable:
        type: boolean
      task-created-on:
        type: string
        format: date-time
      task-activation-time:
        type: string
        format: date-time
      task-proc-inst-id:
        type: integer
      task-proc-def-id:
        type: string
      task-container-id:
        type: string
      task-parent-id:
        type: integer
  
  TaskInstancesWithVars:
    type: object
    properties: 
      task-instance: 
        type: array
        items:
          $ref: "#/definitions/TaskWithVars"
        
  TaskWithVars:
    type: object
    properties:
      task-id:
        type: integer
      task-priority:
        type: integer
      task-name:
        type: string
      task-description:
        type: string
      task-status:
        type: string
      task-actual-owner:
        type: string
      task-created-by:
        type: string
      task-created-on:
        type: string
        format: date-time
      task-activation-time:
        type: string
        format: date-time
      task-process-instance-id:
        type: integer
      task-process-id:
        type: string
      task-container-id:
        type: string
      task-input-data:      
        type: object
        additionalProperties:
          type: string