
swagger: '2.0'
info:
  version: 1.0-SNAPSHOT
  title: KieServerProcessManager
host: kie-dev.svmintranet.com
basePath: /kie-server/services/rest
schemes:
  - https
securityDefinitions:
  tokenAuth:
    type: apiKey
    name: Authorization
    in: header
paths:

  /server/containers/{containerId}/processes/instances/{pInstanceId}/signal/{signalName}:
    post:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: string
          name: pInstanceId
          in: path
          required: true
        - type: string
          name: signalName
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            type: object
            additionalProperties:
                type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/containers/{containerId}/processes/definitions/{processId}:
    get:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: string
          name: processId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: '#/definitions/ProcessDefinition'
              
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/queries/containers/{containerId}/processes/definitions/:
    get:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: '#/definitions/ProcessDefinitions'
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/containers/{id}/processes/{pId}/instances:
    post:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: string
          name: pId
          in: path
          required: true
        - name: body
          in: body
          required: false
          schema:
            type: object
            additionalProperties:
                type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '201':
          description: Created
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/queries/containers/{id}/process/instances:
    get:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: integer
          name: status
          in: query
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/ProcessInstances"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/queries/processes/instances/{pInstanceId}:
    get:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: integer
          name: pInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/ProcessInstance"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers/{id}/processes/instances/{pInstanceId}:
    delete:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: id
          in: path
          required: true
        - type: integer
          name: pInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string
            
  /server/containers:
    get:
      security:
        - tokenAuth: []
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            $ref: "#/definitions/KieContainersStatus"
        '500':
          description: Internal Server Error
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: string

  /server/containers/{containerId}/processes/instances/{pInstanceId}/variables:
    get:
      security:
        - tokenAuth: []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: pInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: object

definitions:

  ServiceResponse:
    type: object
    properties:
      Message:
        type: string
      WorkerName:
        type: string
      Data:
        type: object
      DataType:
        type: string
      SignalInstanceInfo:
        type: object
        properties:
          ContainerId:
            type: string
          ProcessInstanceId:
            type: string
          SignalName:
            type: string
      WorkerCallState:
        type: object
        properties:
          Completed:
            type: boolean
          Errors:
            type: array
            items:
              $ref: "#/definitions/WorkerError"

  WorkerError:
    type: object
    properties:
      ErrorID:
        type: string
      Description:
        type: string
      Severity:
        type: string
        enum: [Warning, Severe, Critical]

  KieContainersStatus:
    type: object
    properties:
      type:
        type: string
      msg: 
        type: string
      result:
        type: object
        properties:
          kie-containers:
            type: object
            properties:
              kie-container:
                type: array
                items:
                  $ref: "#/definitions/KieContainer"
                
  KieContainer:
    type: object
    properties:
      status:
        type: string
      messages:
        type: array
        items:
          type: object
          properties:
            severity:
              type: string
            timestamp:
              type: string
              format: date-time
            content:
              type: array
              items:
                type:
                  string
      container-id: 
        type: string
      release-id:
        type: object
        properties:
          version:
            type: string
          group-id:
            type: string
          artifact-id:
            type: string
      resolved-release-id:
        type: object
        properties:
          version:
            type: string
          group-id:
            type: string
          artifact-id:
            type: string
      
  ProcessInstances:
    type: object
    properties:
      process-instance:
        type: array
        items:
          $ref: "#/definitions/ProcessInstance"
          
  ProcessInstance:
    type: object
    properties:
      initiator:
        type: string
      process-instance-id:
        type: integer
      process-id:
        type: string
      process-name:
        type: string
      process-version:
        type: string
      process-instance-state:
        type: integer
      container-id:
        type: string
      start-date:
        type: string
        format: date-time
      process-instance-desc:
        type: string
      correlation-key:
        type: string
      parent-instance-id:
        type: integer

  ProcessDefinitions:
    type: object
    properties:
      processes:
        type: array
        items:
          $ref: "#/definitions/ProcessDefinition"

  ProcessDefinition:
    type: object
    properties:
      process-id:
        type: string
      process-name:
        type: string
      process-version:
        type: string
      package:
        type: string
      container-id:
        type: string
      process-variables:
        type: object
        additionalProperties:
            type: string

  PaymentData:
    type: object
    properties:
      PaymentId:
        type: string
      RetryId:
        type: string

  IncidentData:
    type: object
    properties:
      SupportActivityId:
        type: string
      OrganizationId:
        type: string
      IncidentType:
        type: string