/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProcessDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinition
        //private ProcessDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessDefinition
            //instance = new ProcessDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessDefinition
        /// </summary>
        [Test]
        public void ProcessDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessDefinition
            //Assert.IsInstanceOfType<ProcessDefinition> (instance, "variable 'instance' is a ProcessDefinition");
        }

        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'ProcessName'
        /// </summary>
        [Test]
        public void ProcessNameTest()
        {
            // TODO unit test for the property 'ProcessName'
        }
        /// <summary>
        /// Test the property 'ProcessVersion'
        /// </summary>
        [Test]
        public void ProcessVersionTest()
        {
            // TODO unit test for the property 'ProcessVersion'
        }
        /// <summary>
        /// Test the property 'Package'
        /// </summary>
        [Test]
        public void PackageTest()
        {
            // TODO unit test for the property 'Package'
        }
        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'ProcessVariables'
        /// </summary>
        [Test]
        public void ProcessVariablesTest()
        {
            // TODO unit test for the property 'ProcessVariables'
        }

    }

}
