/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProcessInstances
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessInstancesTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstances
        //private ProcessInstances instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstances
            //instance = new ProcessInstances();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstances
        /// </summary>
        [Test]
        public void ProcessInstancesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessInstances
            //Assert.IsInstanceOfType<ProcessInstances> (instance, "variable 'instance' is a ProcessInstances");
        }

        /// <summary>
        /// Test the property 'ProcessInstance'
        /// </summary>
        [Test]
        public void ProcessInstanceTest()
        {
            // TODO unit test for the property 'ProcessInstance'
        }

    }

}
