/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceResponseTests
    {
        // TODO uncomment below to declare an instance variable for ServiceResponse
        //private ServiceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceResponse
            //instance = new ServiceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceResponse
        /// </summary>
        [Test]
        public void ServiceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceResponse
            //Assert.IsInstanceOfType<ServiceResponse> (instance, "variable 'instance' is a ServiceResponse");
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'WorkerName'
        /// </summary>
        [Test]
        public void WorkerNameTest()
        {
            // TODO unit test for the property 'WorkerName'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'WorkerCallState'
        /// </summary>
        [Test]
        public void WorkerCallStateTest()
        {
            // TODO unit test for the property 'WorkerCallState'
        }

    }

}
