/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WorkerError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkerErrorTests
    {
        // TODO uncomment below to declare an instance variable for WorkerError
        //private WorkerError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkerError
            //instance = new WorkerError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkerError
        /// </summary>
        [Test]
        public void WorkerErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkerError
            //Assert.IsInstanceOfType<WorkerError> (instance, "variable 'instance' is a WorkerError");
        }

        /// <summary>
        /// Test the property 'ErrorID'
        /// </summary>
        [Test]
        public void ErrorIDTest()
        {
            // TODO unit test for the property 'ErrorID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Test]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }

    }

}
