swagger: '2.0'
info:
  version: 0.1-SNAPSHOT
  title: project
host: localhost:8081
basePath: /kie-server/services/rest
schemes:
  - http
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /server/containers/{containerId}/processes/instances/{pInstanceId}/variables:
    get:
      security:
        - basicAuth : []
      consumes: []
      produces:
        - application/json
        - application/xml
      parameters:
        - type: string
          name: containerId
          in: path
          required: true
        - type: integer
          name: pInstanceId
          in: path
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              type: string
            Content-Language:
              type: string
          schema:
            type: object
