/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// KieContainersStatusResultKiecontainers
    /// </summary>
    [DataContract]
    public partial class KieContainersStatusResultKiecontainers :  IEquatable<KieContainersStatusResultKiecontainers>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KieContainersStatusResultKiecontainers" /> class.
        /// </summary>
        /// <param name="KieContainer">KieContainer.</param>
        public KieContainersStatusResultKiecontainers(List<KieContainer> KieContainer = default(List<KieContainer>))
        {
            this.KieContainer = KieContainer;
        }
        
        /// <summary>
        /// Gets or Sets KieContainer
        /// </summary>
        [DataMember(Name="kie-container", EmitDefaultValue=false)]
        public List<KieContainer> KieContainer { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KieContainersStatusResultKiecontainers {\n");
            sb.Append("  KieContainer: ").Append(KieContainer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KieContainersStatusResultKiecontainers);
        }

        /// <summary>
        /// Returns true if KieContainersStatusResultKiecontainers instances are equal
        /// </summary>
        /// <param name="other">Instance of KieContainersStatusResultKiecontainers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KieContainersStatusResultKiecontainers other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.KieContainer == other.KieContainer ||
                    this.KieContainer != null &&
                    this.KieContainer.SequenceEqual(other.KieContainer)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.KieContainer != null)
                    hash = hash * 59 + this.KieContainer.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
