/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PaymentData
    /// </summary>
    [DataContract]
    public partial class PaymentData :  IEquatable<PaymentData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentData" /> class.
        /// </summary>
        /// <param name="PaymentId">PaymentId.</param>
        /// <param name="RetryId">RetryId.</param>
        public PaymentData(string PaymentId = default(string), string RetryId = default(string))
        {
            this.PaymentId = PaymentId;
            this.RetryId = RetryId;
        }
        
        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [DataMember(Name="PaymentId", EmitDefaultValue=false)]
        public string PaymentId { get; set; }
        /// <summary>
        /// Gets or Sets RetryId
        /// </summary>
        [DataMember(Name="RetryId", EmitDefaultValue=false)]
        public string RetryId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentData {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  RetryId: ").Append(RetryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PaymentData);
        }

        /// <summary>
        /// Returns true if PaymentData instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PaymentId == other.PaymentId ||
                    this.PaymentId != null &&
                    this.PaymentId.Equals(other.PaymentId)
                ) && 
                (
                    this.RetryId == other.RetryId ||
                    this.RetryId != null &&
                    this.RetryId.Equals(other.RetryId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PaymentId != null)
                    hash = hash * 59 + this.PaymentId.GetHashCode();
                if (this.RetryId != null)
                    hash = hash * 59 + this.RetryId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
