/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ServiceResponseSignalInstanceInfo
    /// </summary>
    [DataContract]
    public partial class ServiceResponseSignalInstanceInfo :  IEquatable<ServiceResponseSignalInstanceInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceResponseSignalInstanceInfo" /> class.
        /// </summary>
        /// <param name="ContainerId">ContainerId.</param>
        /// <param name="ProcessInstanceId">ProcessInstanceId.</param>
        /// <param name="SignalName">SignalName.</param>
        public ServiceResponseSignalInstanceInfo(string ContainerId = default(string), string ProcessInstanceId = default(string), string SignalName = default(string))
        {
            this.ContainerId = ContainerId;
            this.ProcessInstanceId = ProcessInstanceId;
            this.SignalName = SignalName;
        }
        
        /// <summary>
        /// Gets or Sets ContainerId
        /// </summary>
        [DataMember(Name="ContainerId", EmitDefaultValue=false)]
        public string ContainerId { get; set; }
        /// <summary>
        /// Gets or Sets ProcessInstanceId
        /// </summary>
        [DataMember(Name="ProcessInstanceId", EmitDefaultValue=false)]
        public string ProcessInstanceId { get; set; }
        /// <summary>
        /// Gets or Sets SignalName
        /// </summary>
        [DataMember(Name="SignalName", EmitDefaultValue=false)]
        public string SignalName { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceResponseSignalInstanceInfo {\n");
            sb.Append("  ContainerId: ").Append(ContainerId).Append("\n");
            sb.Append("  ProcessInstanceId: ").Append(ProcessInstanceId).Append("\n");
            sb.Append("  SignalName: ").Append(SignalName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ServiceResponseSignalInstanceInfo);
        }

        /// <summary>
        /// Returns true if ServiceResponseSignalInstanceInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceResponseSignalInstanceInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceResponseSignalInstanceInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ContainerId == other.ContainerId ||
                    this.ContainerId != null &&
                    this.ContainerId.Equals(other.ContainerId)
                ) && 
                (
                    this.ProcessInstanceId == other.ProcessInstanceId ||
                    this.ProcessInstanceId != null &&
                    this.ProcessInstanceId.Equals(other.ProcessInstanceId)
                ) && 
                (
                    this.SignalName == other.SignalName ||
                    this.SignalName != null &&
                    this.SignalName.Equals(other.SignalName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ContainerId != null)
                    hash = hash * 59 + this.ContainerId.GetHashCode();
                if (this.ProcessInstanceId != null)
                    hash = hash * 59 + this.ProcessInstanceId.GetHashCode();
                if (this.SignalName != null)
                    hash = hash * 59 + this.SignalName.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
