/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WorkerError
    /// </summary>
    [DataContract]
    public partial class WorkerError :  IEquatable<WorkerError>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SeverityEnum
        {
            
            /// <summary>
            /// Enum Warning for "Warning"
            /// </summary>
            [EnumMember(Value = "Warning")]
            Warning,
            
            /// <summary>
            /// Enum Severe for "Severe"
            /// </summary>
            [EnumMember(Value = "Severe")]
            Severe,
            
            /// <summary>
            /// Enum Critical for "Critical"
            /// </summary>
            [EnumMember(Value = "Critical")]
            Critical
        }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [DataMember(Name="Severity", EmitDefaultValue=false)]
        public SeverityEnum? Severity { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerError" /> class.
        /// </summary>
        /// <param name="ErrorID">ErrorID.</param>
        /// <param name="Description">Description.</param>
        /// <param name="Severity">Severity.</param>
        public WorkerError(string ErrorID = default(string), string Description = default(string), SeverityEnum? Severity = default(SeverityEnum?))
        {
            this.ErrorID = ErrorID;
            this.Description = Description;
            this.Severity = Severity;
        }
        
        /// <summary>
        /// Gets or Sets ErrorID
        /// </summary>
        [DataMember(Name="ErrorID", EmitDefaultValue=false)]
        public string ErrorID { get; set; }
        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkerError {\n");
            sb.Append("  ErrorID: ").Append(ErrorID).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as WorkerError);
        }

        /// <summary>
        /// Returns true if WorkerError instances are equal
        /// </summary>
        /// <param name="other">Instance of WorkerError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkerError other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ErrorID == other.ErrorID ||
                    this.ErrorID != null &&
                    this.ErrorID.Equals(other.ErrorID)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.Severity == other.Severity ||
                    this.Severity != null &&
                    this.Severity.Equals(other.Severity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ErrorID != null)
                    hash = hash * 59 + this.ErrorID.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.Severity != null)
                    hash = hash * 59 + this.Severity.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
