/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProcessInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessInstanceTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstance
        //private ProcessInstance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstance
            //instance = new ProcessInstance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstance
        /// </summary>
        [Test]
        public void ProcessInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessInstance
            //Assert.IsInstanceOfType<ProcessInstance> (instance, "variable 'instance' is a ProcessInstance");
        }

        /// <summary>
        /// Test the property 'Initiator'
        /// </summary>
        [Test]
        public void InitiatorTest()
        {
            // TODO unit test for the property 'Initiator'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'ProcessName'
        /// </summary>
        [Test]
        public void ProcessNameTest()
        {
            // TODO unit test for the property 'ProcessName'
        }
        /// <summary>
        /// Test the property 'ProcessVersion'
        /// </summary>
        [Test]
        public void ProcessVersionTest()
        {
            // TODO unit test for the property 'ProcessVersion'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceState'
        /// </summary>
        [Test]
        public void ProcessInstanceStateTest()
        {
            // TODO unit test for the property 'ProcessInstanceState'
        }
        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceDesc'
        /// </summary>
        [Test]
        public void ProcessInstanceDescTest()
        {
            // TODO unit test for the property 'ProcessInstanceDesc'
        }
        /// <summary>
        /// Test the property 'CorrelationKey'
        /// </summary>
        [Test]
        public void CorrelationKeyTest()
        {
            // TODO unit test for the property 'CorrelationKey'
        }
        /// <summary>
        /// Test the property 'ParentInstanceId'
        /// </summary>
        [Test]
        public void ParentInstanceIdTest()
        {
            // TODO unit test for the property 'ParentInstanceId'
        }

    }

}
