/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProcessInstanceList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessInstanceListTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceList
        //private ProcessInstanceList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstanceList
            //instance = new ProcessInstanceList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstanceList
        /// </summary>
        [Test]
        public void ProcessInstanceListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessInstanceList
            //Assert.IsInstanceOfType<ProcessInstanceList> (instance, "variable 'instance' is a ProcessInstanceList");
        }


    }

}
