/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskSummaryTests
    {
        // TODO uncomment below to declare an instance variable for TaskSummary
        //private TaskSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskSummary
            //instance = new TaskSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskSummary
        /// </summary>
        [Test]
        public void TaskSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskSummary
            //Assert.IsInstanceOfType<TaskSummary> (instance, "variable 'instance' is a TaskSummary");
        }

        /// <summary>
        /// Test the property '_TaskSummary'
        /// </summary>
        [Test]
        public void _TaskSummaryTest()
        {
            // TODO unit test for the property '_TaskSummary'
        }

    }

}
