/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Filter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterTests
    {
        // TODO uncomment below to declare an instance variable for Filter
        //private Filter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Filter
            //instance = new Filter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Filter
        /// </summary>
        [Test]
        public void FilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Filter
            //Assert.IsInstanceOfType<Filter> (instance, "variable 'instance' is a Filter");
        }

        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Test]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'OrderAsc'
        /// </summary>
        [Test]
        public void OrderAscTest()
        {
            // TODO unit test for the property 'OrderAsc'
        }
        /// <summary>
        /// Test the property 'QueryParams'
        /// </summary>
        [Test]
        public void QueryParamsTest()
        {
            // TODO unit test for the property 'QueryParams'
        }

    }

}
