/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FilterQueryparams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterQueryparamsTests
    {
        // TODO uncomment below to declare an instance variable for FilterQueryparams
        //private FilterQueryparams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilterQueryparams
            //instance = new FilterQueryparams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilterQueryparams
        /// </summary>
        [Test]
        public void FilterQueryparamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilterQueryparams
            //Assert.IsInstanceOfType<FilterQueryparams> (instance, "variable 'instance' is a FilterQueryparams");
        }

        /// <summary>
        /// Test the property 'CondColumn'
        /// </summary>
        [Test]
        public void CondColumnTest()
        {
            // TODO unit test for the property 'CondColumn'
        }
        /// <summary>
        /// Test the property 'CondOperator'
        /// </summary>
        [Test]
        public void CondOperatorTest()
        {
            // TODO unit test for the property 'CondOperator'
        }
        /// <summary>
        /// Test the property 'CondValues'
        /// </summary>
        [Test]
        public void CondValuesTest()
        {
            // TODO unit test for the property 'CondValues'
        }

    }

}
