/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KieContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KieContainerTests
    {
        // TODO uncomment below to declare an instance variable for KieContainer
        //private KieContainer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KieContainer
            //instance = new KieContainer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KieContainer
        /// </summary>
        [Test]
        public void KieContainerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KieContainer
            //Assert.IsInstanceOfType<KieContainer> (instance, "variable 'instance' is a KieContainer");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'ReleaseId'
        /// </summary>
        [Test]
        public void ReleaseIdTest()
        {
            // TODO unit test for the property 'ReleaseId'
        }
        /// <summary>
        /// Test the property 'ResolvedReleaseId'
        /// </summary>
        [Test]
        public void ResolvedReleaseIdTest()
        {
            // TODO unit test for the property 'ResolvedReleaseId'
        }

    }

}
