/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskSummaries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskSummariesTests
    {
        // TODO uncomment below to declare an instance variable for TaskSummaries
        //private TaskSummaries instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskSummaries
            //instance = new TaskSummaries();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskSummaries
        /// </summary>
        [Test]
        public void TaskSummariesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskSummaries
            //Assert.IsInstanceOfType<TaskSummaries> (instance, "variable 'instance' is a TaskSummaries");
        }

        /// <summary>
        /// Test the property 'TaskSummary'
        /// </summary>
        [Test]
        public void TaskSummaryTest()
        {
            // TODO unit test for the property 'TaskSummary'
        }

    }

}
