/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskInstanceTests
    {
        // TODO uncomment below to declare an instance variable for TaskInstance
        //private TaskInstance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskInstance
            //instance = new TaskInstance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskInstance
        /// </summary>
        [Test]
        public void TaskInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskInstance
            //Assert.IsInstanceOfType<TaskInstance> (instance, "variable 'instance' is a TaskInstance");
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'TaskPriority'
        /// </summary>
        [Test]
        public void TaskPriorityTest()
        {
            // TODO unit test for the property 'TaskPriority'
        }
        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Test]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
        /// <summary>
        /// Test the property 'TaskDescription'
        /// </summary>
        [Test]
        public void TaskDescriptionTest()
        {
            // TODO unit test for the property 'TaskDescription'
        }
        /// <summary>
        /// Test the property 'TaskStatus'
        /// </summary>
        [Test]
        public void TaskStatusTest()
        {
            // TODO unit test for the property 'TaskStatus'
        }
        /// <summary>
        /// Test the property 'TaskActualOwner'
        /// </summary>
        [Test]
        public void TaskActualOwnerTest()
        {
            // TODO unit test for the property 'TaskActualOwner'
        }
        /// <summary>
        /// Test the property 'TaskCreatedBy'
        /// </summary>
        [Test]
        public void TaskCreatedByTest()
        {
            // TODO unit test for the property 'TaskCreatedBy'
        }
        /// <summary>
        /// Test the property 'TaskCreatedOn'
        /// </summary>
        [Test]
        public void TaskCreatedOnTest()
        {
            // TODO unit test for the property 'TaskCreatedOn'
        }
        /// <summary>
        /// Test the property 'TaskActivationTime'
        /// </summary>
        [Test]
        public void TaskActivationTimeTest()
        {
            // TODO unit test for the property 'TaskActivationTime'
        }
        /// <summary>
        /// Test the property 'TaskProcessInstanceId'
        /// </summary>
        [Test]
        public void TaskProcessInstanceIdTest()
        {
            // TODO unit test for the property 'TaskProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'TaskProcessId'
        /// </summary>
        [Test]
        public void TaskProcessIdTest()
        {
            // TODO unit test for the property 'TaskProcessId'
        }
        /// <summary>
        /// Test the property 'TaskContainerId'
        /// </summary>
        [Test]
        public void TaskContainerIdTest()
        {
            // TODO unit test for the property 'TaskContainerId'
        }
        /// <summary>
        /// Test the property 'TaskInputData'
        /// </summary>
        [Test]
        public void TaskInputDataTest()
        {
            // TODO unit test for the property 'TaskInputData'
        }

    }

}
