/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskTests
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Test]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Task
            //Assert.IsInstanceOfType<Task> (instance, "variable 'instance' is a Task");
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Test]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
        /// <summary>
        /// Test the property 'TaskSubject'
        /// </summary>
        [Test]
        public void TaskSubjectTest()
        {
            // TODO unit test for the property 'TaskSubject'
        }
        /// <summary>
        /// Test the property 'TaskDescription'
        /// </summary>
        [Test]
        public void TaskDescriptionTest()
        {
            // TODO unit test for the property 'TaskDescription'
        }
        /// <summary>
        /// Test the property 'TaskStatus'
        /// </summary>
        [Test]
        public void TaskStatusTest()
        {
            // TODO unit test for the property 'TaskStatus'
        }
        /// <summary>
        /// Test the property 'TaskPriority'
        /// </summary>
        [Test]
        public void TaskPriorityTest()
        {
            // TODO unit test for the property 'TaskPriority'
        }
        /// <summary>
        /// Test the property 'TaskIsSkipable'
        /// </summary>
        [Test]
        public void TaskIsSkipableTest()
        {
            // TODO unit test for the property 'TaskIsSkipable'
        }
        /// <summary>
        /// Test the property 'TaskCreatedOn'
        /// </summary>
        [Test]
        public void TaskCreatedOnTest()
        {
            // TODO unit test for the property 'TaskCreatedOn'
        }
        /// <summary>
        /// Test the property 'TaskActivationTime'
        /// </summary>
        [Test]
        public void TaskActivationTimeTest()
        {
            // TODO unit test for the property 'TaskActivationTime'
        }
        /// <summary>
        /// Test the property 'TaskProcInstId'
        /// </summary>
        [Test]
        public void TaskProcInstIdTest()
        {
            // TODO unit test for the property 'TaskProcInstId'
        }
        /// <summary>
        /// Test the property 'TaskProcDefId'
        /// </summary>
        [Test]
        public void TaskProcDefIdTest()
        {
            // TODO unit test for the property 'TaskProcDefId'
        }
        /// <summary>
        /// Test the property 'TaskContainerId'
        /// </summary>
        [Test]
        public void TaskContainerIdTest()
        {
            // TODO unit test for the property 'TaskContainerId'
        }
        /// <summary>
        /// Test the property 'TaskParentId'
        /// </summary>
        [Test]
        public void TaskParentIdTest()
        {
            // TODO unit test for the property 'TaskParentId'
        }

    }

}
