/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IncidentData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IncidentDataTests
    {
        // TODO uncomment below to declare an instance variable for IncidentData
        //private IncidentData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IncidentData
            //instance = new IncidentData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IncidentData
        /// </summary>
        [Test]
        public void IncidentDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IncidentData
            //Assert.IsInstanceOfType<IncidentData> (instance, "variable 'instance' is a IncidentData");
        }

        /// <summary>
        /// Test the property 'SupportActivityId'
        /// </summary>
        [Test]
        public void SupportActivityIdTest()
        {
            // TODO unit test for the property 'SupportActivityId'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Test]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'IncidentType'
        /// </summary>
        [Test]
        public void IncidentTypeTest()
        {
            // TODO unit test for the property 'IncidentType'
        }

    }

}
