/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KieContainersStatusResultKiecontainers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KieContainersStatusResultKiecontainersTests
    {
        // TODO uncomment below to declare an instance variable for KieContainersStatusResultKiecontainers
        //private KieContainersStatusResultKiecontainers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KieContainersStatusResultKiecontainers
            //instance = new KieContainersStatusResultKiecontainers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KieContainersStatusResultKiecontainers
        /// </summary>
        [Test]
        public void KieContainersStatusResultKiecontainersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KieContainersStatusResultKiecontainers
            //Assert.IsInstanceOfType<KieContainersStatusResultKiecontainers> (instance, "variable 'instance' is a KieContainersStatusResultKiecontainers");
        }

        /// <summary>
        /// Test the property 'KieContainer'
        /// </summary>
        [Test]
        public void KieContainerTest()
        {
            // TODO unit test for the property 'KieContainer'
        }

    }

}
