/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceResponseSignalInstanceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceResponseSignalInstanceInfoTests
    {
        // TODO uncomment below to declare an instance variable for ServiceResponseSignalInstanceInfo
        //private ServiceResponseSignalInstanceInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceResponseSignalInstanceInfo
            //instance = new ServiceResponseSignalInstanceInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceResponseSignalInstanceInfo
        /// </summary>
        [Test]
        public void ServiceResponseSignalInstanceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceResponseSignalInstanceInfo
            //Assert.IsInstanceOfType<ServiceResponseSignalInstanceInfo> (instance, "variable 'instance' is a ServiceResponseSignalInstanceInfo");
        }

        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'SignalName'
        /// </summary>
        [Test]
        public void SignalNameTest()
        {
            // TODO unit test for the property 'SignalName'
        }

    }

}
