/* 
 * KieServerTaskManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Mapper
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Mapper
    {
        
        /// <summary>
        /// Enum UserTasksWithCustomVariables for "UserTasksWithCustomVariables"
        /// </summary>
        [EnumMember(Value = "UserTasksWithCustomVariables")]
        UserTasksWithCustomVariables,
        
        /// <summary>
        /// Enum UserTasksWithVariables for "UserTasksWithVariables"
        /// </summary>
        [EnumMember(Value = "UserTasksWithVariables")]
        UserTasksWithVariables,
        
        /// <summary>
        /// Enum UserTasks for "UserTasks"
        /// </summary>
        [EnumMember(Value = "UserTasks")]
        UserTasks,
        
        /// <summary>
        /// Enum ProcessInstancesWithCustomVariables for "ProcessInstancesWithCustomVariables"
        /// </summary>
        [EnumMember(Value = "ProcessInstancesWithCustomVariables")]
        ProcessInstancesWithCustomVariables,
        
        /// <summary>
        /// Enum ProcessInstancesWithVariables for "ProcessInstancesWithVariables"
        /// </summary>
        [EnumMember(Value = "ProcessInstancesWithVariables")]
        ProcessInstancesWithVariables,
        
        /// <summary>
        /// Enum ProcessInstances for "ProcessInstances"
        /// </summary>
        [EnumMember(Value = "ProcessInstances")]
        ProcessInstances,
        
        /// <summary>
        /// Enum TaskSummaries for "TaskSummaries"
        /// </summary>
        [EnumMember(Value = "TaskSummaries")]
        TaskSummaries,
        
        /// <summary>
        /// Enum RawList for "RawList"
        /// </summary>
        [EnumMember(Value = "RawList")]
        RawList
    }

}
