/* 
 * KieServerTaskManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TaskSummaries
    /// </summary>
    [DataContract]
    public partial class TaskSummaries :  IEquatable<TaskSummaries>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskSummaries" /> class.
        /// </summary>
        /// <param name="TaskSummary">TaskSummary.</param>
        public TaskSummaries(List<TaskSummary> TaskSummary = default(List<TaskSummary>))
        {
            this.TaskSummary = TaskSummary;
        }
        
        /// <summary>
        /// Gets or Sets TaskSummary
        /// </summary>
        [DataMember(Name="task-summary", EmitDefaultValue=false)]
        public List<TaskSummary> TaskSummary { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaskSummaries {\n");
            sb.Append("  TaskSummary: ").Append(TaskSummary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TaskSummaries);
        }

        /// <summary>
        /// Returns true if TaskSummaries instances are equal
        /// </summary>
        /// <param name="other">Instance of TaskSummaries to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskSummaries other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TaskSummary == other.TaskSummary ||
                    this.TaskSummary != null &&
                    this.TaskSummary.SequenceEqual(other.TaskSummary)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TaskSummary != null)
                    hash = hash * 59 + this.TaskSummary.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
