/* 
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TaskInstancesWithVars
    /// </summary>
    [DataContract]
    public partial class TaskInstancesWithVars :  IEquatable<TaskInstancesWithVars>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskInstancesWithVars" /> class.
        /// </summary>
        /// <param name="TaskInstance">TaskInstance.</param>
        public TaskInstancesWithVars(List<TaskWithVars> TaskInstance = default(List<TaskWithVars>))
        {
            this.TaskInstance = TaskInstance;
        }
        
        /// <summary>
        /// Gets or Sets TaskInstance
        /// </summary>
        [DataMember(Name="task-instance", EmitDefaultValue=false)]
        public List<TaskWithVars> TaskInstance { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaskInstancesWithVars {\n");
            sb.Append("  TaskInstance: ").Append(TaskInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TaskInstancesWithVars);
        }

        /// <summary>
        /// Returns true if TaskInstancesWithVars instances are equal
        /// </summary>
        /// <param name="other">Instance of TaskInstancesWithVars to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskInstancesWithVars other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TaskInstance == other.TaskInstance ||
                    this.TaskInstance != null &&
                    this.TaskInstance.SequenceEqual(other.TaskInstance)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TaskInstance != null)
                    hash = hash * 59 + this.TaskInstance.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
