/*
 * project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TaskApiTests
    {
        private DefaultApi instance;
        private int? taskInstanceId;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi("http://10.52.36.22:8080/kie-server/services/rest");
            instance.Configuration.ApiKey.Add("Authorization","eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkF1ZHBIa0tnS2lhZ3Q2U0pxajdVcjFRX3M5USJ9.eyJhdWQiOiJodHRwczovL3d3dy5zZXJ2c21hcnQuc2VydmljZW1hc3Rlci5jb20iLCJpc3MiOiJodHRwOi8vYWRmcy5zZXJ2aWNlbWFzdGVyLmNvbS9hZGZzL3NlcnZpY2VzL3RydXN0IiwiaWF0IjoxNDg3MTg2Mjc4LCJleHAiOjE0ODcyNDAyNzgsIndpbmFjY291bnRuYW1lIjoianJvbGZlIiwiZ3JvdXAiOlsiRG9tYWluIFVzZXJzIiwiU2hhcmVmaWxlIFVzZXJzIiwiQXBwRHluYW1pY3NfQ3VzdG9tX0Rhc2hib2FyZF9WaWV3ZXIiLCJBcHBEeW5hbWljc19EQl9Nb25pdG9yaW5nX1VzZXIiLCJBcHBEeW5hbWljc19TZXJ2ZXJfTW9uaXRvcmluZ19Vc2VyIiwiQXBwRHluYW1pY3NfUmVhZF9Pbmx5X1VzZXIiXSwiYXV0aF90aW1lIjoiMjAxNy0wMi0xNVQxOToxNzo1OC4yNDNaIiwiYXV0aG1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0IiwidmVyIjoiMS4wIiwiYXBwaWQiOiJhZHByb2QifQ.nuw5PwhfF4C8Bu4CWOQd89aMg4mU8mTh5IB7r9QxHvTfrqKY5N7sVVrzVaFqWR-jm_CF8Rfcp-Yc9_2SltIMJo0WRs_JaEIXU9tX4pvudWsA8pC_ZQ5mcov3oVvxqTD61pI5S1u3FDSIFzTzwDhI-PTCsL4av6XnDdtQw9QHhNxkHQW_JYw_ikCq_tJzMtst6IUnSRZUvmH0XRklOY9ts8Mn3xMgb5arEdVobiL8lzUA1vxk-_DYSIDPFAneIgW9Aycoj9O7twoOvfOzrFNL-mgT_sulxaIuvQsSRheHTfUwByIwU1Hkgq02WhJnhGeAjagOsbTkAoZgRh_EHev_DA");
            instance.Configuration.ApiClient.AddToTypeRegistry("svm.hello_bpm.Person", typeof(Person));
            ServerQueriesTasksInstancesPotOwnersGetTest();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
            instance.Configuration.ApiClient.clearTypeRegistry();
            ServerQueriesTasksInstancesPotOwnersGetTest();
        }

        [Test]
        public void endToEndTest()
        {
            ServerQueriesTasksInstancesPotOwnersGetTest();
            ServerContainersContainerIdTasksTInstanceIdStatesClaimedPutTest();
            ServerContainersContainerIdTasksTInstanceIdStatesStartedPutTest();
            ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutObjectParamTest();
            ServerQueriesTasksInstancesPotOwnersGetTest();
            ServerContainersContainerIdTasksTInstanceIdStatesClaimedPutTest();
            ServerContainersContainerIdTasksTInstanceIdStatesStartedPutTest();
            ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutAtomicParamTest();
//            ServerQueriesTasksInstancesPotOwnersGetTest();
//            ServerContainersContainerIdTasksTInstanceIdStatesClaimedPutTest();
//            ServerContainersContainerIdTasksTInstanceIdStatesStartedPutTest();
//            ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutNoneParamTest();
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        
        /// <summary>
        /// Test ServerContainersContainerIdTasksTInstanceIdStatesClaimedPut
        /// </summary>
        [Test]
        public void ServerContainersContainerIdTasksTInstanceIdStatesClaimedPutTest()
        {
            string containerId = "SVMContainer";
            int? tInstanceId = taskInstanceId;
            var response = instance.ServerContainersContainerIdTasksTInstanceIdStatesClaimedPut(containerId, tInstanceId);
            Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        [Test]
        public void ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutNoneParamTest()
        {
            string containerId = "SVMContainer";
            int? tInstanceId = taskInstanceId;
            Object body = null;
            var response = instance.ServerContainersContainerIdTasksTInstanceIdStatesCompletedPut(containerId, tInstanceId, body);
            Assert.IsInstanceOf<string> (response, "response is string");
        }

        [Test]
        public void ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutAtomicParamTest()
        {
            string containerId = "SVMContainer";
            int? tInstanceId = taskInstanceId;
            var taskParams = new Dictionary<string, object>();
            taskParams.Add("occupation", "consultant");
            taskParams.Add("salary", 1000);
            var response = instance.ServerContainersContainerIdTasksTInstanceIdStatesCompletedPut(containerId, tInstanceId, taskParams);
            Assert.IsInstanceOf<string> (response, "response is string");
        }

        [Test]
        public void ServerContainersContainerIdTasksTInstanceIdStatesCompletedPutObjectParamTest()
        {
            string containerId = "SVMContainer";
            int? tInstanceId = taskInstanceId;
            Person person = new Person();
            person.name = "nick";
            person.age = 23;
            var taskVars = new Dictionary<string, object>();
            taskVars.Add("person", person);
            var response = instance.ServerContainersContainerIdTasksTInstanceIdStatesCompletedPut(containerId, tInstanceId, taskVars);
            Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ServerContainersContainerIdTasksTInstanceIdStatesStartedPut
        /// </summary>
        [Test]
        public void ServerContainersContainerIdTasksTInstanceIdStatesStartedPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string containerId = "SVMContainer";
            int? tInstanceId = taskInstanceId;
            var response = instance.ServerContainersContainerIdTasksTInstanceIdStatesStartedPut(containerId, tInstanceId);
            Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ServerQueriesTasksInstancesPotOwnersGet
        /// </summary>
        [Test]
        public void ServerQueriesTasksInstancesPotOwnersGetTest()
        {
            List<string> groups = null;
            int? page = null;
            int? pageSize = null;
            string sort = null;
            bool? sortOrder = null;
            List<string> status = null;
            string user = null;
            var response = instance.ServerQueriesTasksInstancesPotOwnersGet(groups, page, pageSize, sort, sortOrder, status, user);
            if (response.TaskSummary.Count > 0)
            {
                Console.WriteLine(response.TaskSummary.ElementAt(0));
                taskInstanceId = response.TaskSummary.ElementAt((0)).TaskId;
            }
            Assert.IsInstanceOf<TaskSummaries> (response, "response is TaskSummary");
        }
    }

}
