/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// KieContainersStatusResult
    /// </summary>
    [DataContract]
    public partial class KieContainersStatusResult :  IEquatable<KieContainersStatusResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KieContainersStatusResult" /> class.
        /// </summary>
        /// <param name="KieContainers">KieContainers.</param>
        public KieContainersStatusResult(KieContainersStatusResultKiecontainers KieContainers = default(KieContainersStatusResultKiecontainers))
        {
            this.KieContainers = KieContainers;
        }
        
        /// <summary>
        /// Gets or Sets KieContainers
        /// </summary>
        [DataMember(Name="kie-containers", EmitDefaultValue=false)]
        public KieContainersStatusResultKiecontainers KieContainers { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KieContainersStatusResult {\n");
            sb.Append("  KieContainers: ").Append(KieContainers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KieContainersStatusResult);
        }

        /// <summary>
        /// Returns true if KieContainersStatusResult instances are equal
        /// </summary>
        /// <param name="other">Instance of KieContainersStatusResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KieContainersStatusResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.KieContainers == other.KieContainers ||
                    this.KieContainers != null &&
                    this.KieContainers.Equals(other.KieContainers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.KieContainers != null)
                    hash = hash * 59 + this.KieContainers.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
