/* 
 * KieServerProcessManager
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// KieContainer
    /// </summary>
    [DataContract]
    public partial class KieContainer :  IEquatable<KieContainer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KieContainer" /> class.
        /// </summary>
        /// <param name="Status">Status.</param>
        /// <param name="Messages">Messages.</param>
        /// <param name="ContainerId">ContainerId.</param>
        /// <param name="ReleaseId">ReleaseId.</param>
        /// <param name="ResolvedReleaseId">ResolvedReleaseId.</param>
        public KieContainer(string Status = default(string), List<KieContainerMessages> Messages = default(List<KieContainerMessages>), string ContainerId = default(string), KieContainerReleaseid ReleaseId = default(KieContainerReleaseid), KieContainerReleaseid ResolvedReleaseId = default(KieContainerReleaseid))
        {
            this.Status = Status;
            this.Messages = Messages;
            this.ContainerId = ContainerId;
            this.ReleaseId = ReleaseId;
            this.ResolvedReleaseId = ResolvedReleaseId;
        }
        
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }
        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [DataMember(Name="messages", EmitDefaultValue=false)]
        public List<KieContainerMessages> Messages { get; set; }
        /// <summary>
        /// Gets or Sets ContainerId
        /// </summary>
        [DataMember(Name="container-id", EmitDefaultValue=false)]
        public string ContainerId { get; set; }
        /// <summary>
        /// Gets or Sets ReleaseId
        /// </summary>
        [DataMember(Name="release-id", EmitDefaultValue=false)]
        public KieContainerReleaseid ReleaseId { get; set; }
        /// <summary>
        /// Gets or Sets ResolvedReleaseId
        /// </summary>
        [DataMember(Name="resolved-release-id", EmitDefaultValue=false)]
        public KieContainerReleaseid ResolvedReleaseId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KieContainer {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  ContainerId: ").Append(ContainerId).Append("\n");
            sb.Append("  ReleaseId: ").Append(ReleaseId).Append("\n");
            sb.Append("  ResolvedReleaseId: ").Append(ResolvedReleaseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KieContainer);
        }

        /// <summary>
        /// Returns true if KieContainer instances are equal
        /// </summary>
        /// <param name="other">Instance of KieContainer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KieContainer other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Messages == other.Messages ||
                    this.Messages != null &&
                    this.Messages.SequenceEqual(other.Messages)
                ) && 
                (
                    this.ContainerId == other.ContainerId ||
                    this.ContainerId != null &&
                    this.ContainerId.Equals(other.ContainerId)
                ) && 
                (
                    this.ReleaseId == other.ReleaseId ||
                    this.ReleaseId != null &&
                    this.ReleaseId.Equals(other.ReleaseId)
                ) && 
                (
                    this.ResolvedReleaseId == other.ResolvedReleaseId ||
                    this.ResolvedReleaseId != null &&
                    this.ResolvedReleaseId.Equals(other.ResolvedReleaseId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.Messages != null)
                    hash = hash * 59 + this.Messages.GetHashCode();
                if (this.ContainerId != null)
                    hash = hash * 59 + this.ContainerId.GetHashCode();
                if (this.ReleaseId != null)
                    hash = hash * 59 + this.ReleaseId.GetHashCode();
                if (this.ResolvedReleaseId != null)
                    hash = hash * 59 + this.ResolvedReleaseId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
